<?php

namespace App\Imports;

use App\RegisterPasien;
use Illuminate\Support\Collection;
use Maatwebsite\Excel\Concerns\ToCollection;
use Maatwebsite\Excel\Concerns\WithHeadingRow;
class RegisterImport implements ToCollection, WithHeadingRow
{
    /**
    * @param array $row
    *
    * @return \Illuminate\Database\Eloquent\Model|null
    */
    public function collection(Collection $rows)
    {
        
        foreach ($rows as $row) 
        {   $insert = new RegisterPasien;
            $insert->insertOrIgnore([
                'reg_no'  => $row['nomor_registrasi'],
                'reg_nik' => $row['nik_pasien'],
                'reg_dinkes_pengirim'    => $row['dinkes_pengirim'],
                'reg_fasyankes_pengirim'    => $row['fasyankes_pengirim'],
                'reg_nama_rs'    => $row['nama_rs'],
                'reg_no_rekammedis'    => $row['no_rekammedis'],
                'reg_nama_dokter'    => $row['nama_dokter'],
                'reg_telp_fas_pengirim'    => $row['telp_fas_pengirim'],
                'reg_nama_pasien'    => $row['nama_pasien'],
                'reg_tanggallahir'    => $row['tanggallahir'],
                'reg_kelamin'    => $row['kelamin'],
                'reg_hamil_pasca'    => $row['hamil_pasca'],
                'reg_alamat'    => $row['alamat'],
                'reg_notelp_pasien'    => $row['notelp_pasien'],
                'reg_tanggalkunjungan1'    => $row['tanggalkunjungan1'],
                'reg_rsfasyankes1'    => $row['rsfasyankes1'],
                'reg_tanggalkunjungan2'    => $row['tanggalkunjungan2'],
                'reg_rsfasyankes2'    => $row['rsfasyankes2'],
                'reg_tanggalkunjungan3'    => $row['tanggalkunjungan3'],
                'reg_rsfasyankes3'    => $row['rsfasyankes3'],
                'reg_tanggalkunjungan4'    => $row['tanggalkunjungan4'],
                'reg_rsfasyankes4'    => $row['rsfasyankes4'],
                'reg_tanggalkunjungan5'    => $row['tanggalkunjungan5'],
                'reg_rsfasyankes5'    => $row['rsfasyankes5'],
                'reg_tanggalkunjungan6'    => $row['tanggalkunjungan6'],
                'reg_rsfasyankes6'    => $row['rsfasyankes6'],
                'reg_tanggalkunjungan7'    => $row['tanggalkunjungan7'],
                'reg_rsfasyankes7'    => $row['rsfasyankes7'],
                'reg_onset_panas'    => $row['onset_panas'],
                'reg_gejpenumonia'    => $row['gejpneumonia'],
                'reg_gejpanas'    => $row['gejpanas'],
                'reg_gejbatuk'    => $row['gejbatuk'],
                'reg_gejnyeritenggorokan'    => $row['gejnyeritenggorokan'],
                'reg_gejsesaknafas'    => $row['gejsesaknafas'],
                'reg_gejpilek'    => $row['gejpilek'],
                'reg_gejlesu'    => $row['gejlesu'],
                'reg_gejsakitkepala'    => $row['gejsakitkepala'],
                'reg_gejdiare'    => $row['gejdiare'],
                'reg_gejmualmuntah'    => $row['gejmualmuntah'],
                'reg_gejlain'    => $row['gejlain'],
                'reg_xrayparu'    => $row['xrayparu'],
                'reg_hasilxray'    => $row['hasilxray'],
                  'reg_leukosit'    => $row['leukosit'],
                  'reg_limfosit'    => $row['limfosit'],
                  'reg_trombosit'    => $row['trombosit'],
                  'reg_ventilator'    => $row['ventilator'],
                  'reg_statuskes'    => $row['statuskes'],
                  'reg_luarnegri'    => $row['berkunjung_ke_luar_negri'],
                  'reg_tanggalkunjungan_pasien1'    => $row['tanggalkunjungan_pasien1'],
                  'reg_kotakunjungan_pasien1'    => $row['kotakunjungan_pasien1'],
                  'reg_negarakunjungan_pasien1'    => $row['negarakunjungan_pasien1'],
                  'reg_tanggalkunjungan_pasien2'    => $row['tanggalkunjungan_pasien2'],
                  'reg_kotakunjungan_pasien2'    => $row['kotakunjungan_pasien2'],
                  'reg_negarakunjungan_pasien2'    => $row['negarakunjungan_pasien2'],
                  'reg_tanggalkunjungan_pasien3'    => $row['tanggalkunjungan_pasien3'],
                  'reg_kotakunjungan_pasien3'    => $row['kotakunjungan_pasien3'],
                  'reg_negarakunjungan_pasien3'    => $row['negarakunjungan_pasien3'],
                  'reg_tanggalkunjungan_pasien4'    => $row['tanggalkunjungan_pasien4'],
                  'reg_kotakunjungan_pasien4'    => $row['kotakunjungan_pasien4'],
                  'reg_negarakunjungan_pasien4'    => $row['negarakunjungan_pasien4'],
                  'reg_tanggalkunjungan_pasien5'    => $row['tanggalkunjungan_pasien5'],
                  'reg_kotakunjungan_pasien5'    => $row['kotakunjungan_pasien5'],
                  'reg_negarakunjungan_pasien5'    => $row['negarakunjungan_pasien5'],
                  'reg_tanggalkunjungan_pasien6'    => $row['tanggalkunjungan_pasien6'],
                  'reg_kotakunjungan_pasien6'    => $row['kotakunjungan_pasien6'],
                  'reg_negarakunjungan_pasien6'    => $row['negarakunjungan_pasien6'],
                  'reg_tanggalkunjungan_pasien7'    => $row['tanggalkunjungan_pasien7'],
                  'reg_kotakunjungan_pasien7'    => $row['kotakunjungan_pasien7'],
                  'reg_negarakunjungan_pasien7'    => $row['negarakunjungan_pasien7'],
                  'reg_kontakdgnsakit'    => $row['kontakdgnsakit'],
                  'reg_namakon1'    => $row['namakon1'],
                  'reg_alamatkon1'    => $row['alamatkon1'],
                  'reg_hubungankon1'    => $row['hubungankon1'],
                  'reg_tanggalkonawal1'    => $row['tanggalkonawal1'],
                  'reg_tanggalkonakhir1'    => $row['tanggalkonakhir1'],
                  'reg_namakon2'    => $row['namakon2'],
                  'reg_alamatkon2'    => $row['alamatkon2'],
                  'reg_hubungankon2'    => $row['hubungankon2'],
                  'reg_tanggalkonawal2'    => $row['tanggalkonawal2'],
                  'reg_tanggalkonakhir2'    => $row['tanggalkonakhir2'],
                  'reg_namakon3'    => $row['namakon3'],
                  'reg_alamatkon3'    => $row['alamatkon3'],
                  'reg_hubungankon3'    => $row['hubungankon3'],
                  'reg_tanggalkonawal3'    => $row['tanggalkonawal3'],
                  'reg_tanggalkonakhir3'    => $row['tanggalkonakhir3'],
                  'reg_namakon4'    => $row['namakon4'],
                  'reg_alamatkon4'    => $row['alamatkon4'],
                  'reg_hubungankon4'    => $row['hubungankon4'],
                  'reg_tanggalkonawal4'    => $row['tanggalkonawal4'],
                  'reg_tanggalkonakhir4'    => $row['tanggalkonakhir4'],
                  'reg_namakon5'    => $row['namakon5'],
                  'reg_alamatkon5'    => $row['alamatkon5'],
                  'reg_hubungankon5'    => $row['hubungankon5'],
                  'reg_tanggalkonawal5'    => $row['tanggalkonawal5'],
                  'reg_tanggalkonakhir5'    => $row['tanggalkonakhir5'],
                  'reg_namakon6'    => $row['namakon6'],
                  'reg_alamatkon6'    => $row['alamatkon6'],
                  'reg_hubungankon6'    => $row['hubungankon6'],
                  'reg_tanggalkonawal6'    => $row['tanggalkonawal6'],
                  'reg_tanggalkonakhir6'    => $row['tanggalkonakhir6'],
                  'reg_namakon7'    => $row['namakon7'],
                  'reg_alamatkon7'    => $row['alamatkon7'],
                  'reg_hubungankon7'    => $row['hubungankon7'],
                  'reg_tanggalkonawal7'    => $row['tanggalkonawal7'],
                  'reg_tanggalkonakhir7'    => $row['tanggalkonakhir7'],
                  'reg_kontakterinfeksi'    => $row['kontakterinfeksi'],
                  'reg_keluargapasiensakitsama'    => $row['keluargapasiensakitsama'],
                  'reg_komorbidhipertensi'    => $row['komorbidhipertensi'],
                  'reg_komorbiddm'    => $row['komorbiddm'],
                  'reg_komorbidliver'    => $row['komorbidliver'],
                  'reg_komorbidneurologi'    => $row['komorbidneurologi'],
                  'reg_komorbidneurologi'    => $row['komorbidhiv'],
                  'reg_komorbidparu'    => $row['komorbidparu'],
                  'reg_komorbidginjal'    => $row['komorbidginjal'],
                  'reg_penjelasanlain'    => $row['penjelasanlain'],
                  'reg_dateinput'    => $row['dateinput'],
                  'reg_userid'    => $row['userid'],
                  'reg_statusreg'    => $row['statusreg'],
             
            ]);
        }
        }
        
}
